;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sal Ara 22 2020
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

ORG 0010H

START:
	MOV DX, 00H
	
	MOV SI, INTRHANDLER
	MOV DI, [0000H]
	MOV [DI], SI
	
	JMP INPUTECHO
	
INPUTECHO:
	INT 0
	CALL PRINTCHAR ;
	JMP INPUTECHO
ENDLESS:
	JMP ENDLESS
PRINTCHAR:
	MOV AL, 0FFH
	CALL SEND
	; SOME DELAY
	MOV CX, 01AH
	LOOP2:
		LOOP LOOP2
	; IDLE
	MOV AL, 00H
	CALL SEND
	; START BIT 
	MOV AL, BL
	CALL SEND
	; BIT 0
	CALL SEND
	; BIT 1
	CALL SEND
	; BIT 2
	CALL SEND
	; BIT 3
	CALL SEND
	; BIT 4
	CALL SEND
	; BIT 5
	CALL SEND
	; BIT 6
	CALL SEND
	; BIT 7
	MOV AL, 0FFH
	CALL SEND
	; STOP BIT
	CALL SEND
	; STOP BIT AGAIN FOR VISUALIZATION
	RET
SEND:
	OUT DX, AL
	ROR AL, 1 
	CALL DELAY
	RET  	 
DELAY:
	MOV CX, 018H     
	LOOP1:
		LOOP LOOP1 
	RET
	
DELAY2:
	NOP
	NOP
	NOP
	NOP
	NOP
	MOV CX, 02H
	LOOP4:
		LOOP LOOP4
	RET
	
INTRHANDLER:
	MOV BX, 0H
	MOV SI, 8H
	IDLE:
		IN AX, DX
		CMP AX, 80H
		JZ IDLE
	CALL DELAY2
	LOOP3:
		CALL DELAY
		MOV CX, SI
		DEC SI
		SHR BX, 1
		IN AX, DX
		OR BX, AX
		LOOP LOOP3
	CALL DELAY
	IRET
	
CODE    ENDS
        END START